#!/bin/bash

echo 'mtr'
echo `date -R`

statFileDir="${HOME}/auto-generate"

if [ ! -d ${statFileDir} ]; then
        mkdir ${statFileDir}
fi

echo ${statFileDir}

mtr jpn.melee.one -c 100 -r -n > ${statFileDir}/mtr.001.LinodeJPN 2>&1 
mtr jpn2.melee.one -c 100 -r -n > ${statFileDir}/mtr.002.LinodeJPN2 2>&1 

exit 0
