#!/bin/bash

echo 'mtr'
echo `date -R`

scriptFileDir=$(cd "$(dirname "$0")"; pwd)
echo ${scriptFileDir}
statFileDir="${HOME}/auto-generate/mtr"
echo ${statFileDir}

if [ ! -d ${statFileDir} ]; then
        mkdir ${statFileDir}
fi

rm -rf ${statFileDir}/*

while read line
do
	fileName="${statFileDir}/mtr.${line}"
    echo ${line}
    mtr -c 20 -r -n ${line} >${fileName}
done < ${scriptFileDir}/mtr.list

