#!/bin/bash

logdir="${HOME}/log"

if [ ! -d ${logdir} ]; then
        mkdir -p ${logdir}
fi

logcn2="${logdir}/vnetcn2"
curl http://106.186.121.152:9999/random.file -o ${logcn2} -v --socks5 127.0.0.1:14000
curl http://106.186.121.152:9999/zero_1MiB.file --socks5 127.0.0.1:14000
